name: dispatch-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  dispatch-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Build in Autoware
        run: |
          repo_owner="autowarefoundation" 
          repo_name="autoware"
          event_type="trigger-nightly-build" 
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"git_hash\": \"$git_hash\", \"unit\": false, \"integration\": true}}"